// <auto-generated />
using System;
using CocktailHub.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CocktailHub.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260310080719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CocktailHub.Core.Entities.Cocktail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsModerated")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Cocktails");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.CocktailIngredient", b =>
                {
                    b.Property<int>("CocktailId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<string>("Measure")
                        .HasColumnType("text");

                    b.HasKey("CocktailId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CocktailIngredients");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsoCode = "US",
                            Name = "USA"
                        },
                        new
                        {
                            Id = 2,
                            IsoCode = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 3,
                            IsoCode = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Id = 4,
                            IsoCode = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 5,
                            IsoCode = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 6,
                            IsoCode = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 7,
                            IsoCode = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 8,
                            IsoCode = "RU",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 9,
                            IsoCode = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 10,
                            IsoCode = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 11,
                            IsoCode = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 12,
                            IsoCode = "DE",
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.Favorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("CocktailId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CocktailId");

                    b.HasIndex("CocktailId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@cocktailhub.com",
                            PasswordHash = "$2a$11$I1K7kMFl4YfH/bgB/Fds9O8vhbLB44LQl5lb/Z4A.neo8AM0ZCn.u",
                            Role = 1
                        });
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.Cocktail", b =>
                {
                    b.HasOne("CocktailHub.Core.Entities.Country", "Country")
                        .WithMany("Cocktails")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailHub.Core.Entities.User", "CreatedByUser")
                        .WithMany("CreatedCocktails")
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("Country");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.CocktailIngredient", b =>
                {
                    b.HasOne("CocktailHub.Core.Entities.Cocktail", "Cocktail")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailHub.Core.Entities.Ingredient", "Ingredient")
                        .WithMany("CocktailIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocktail");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.Favorite", b =>
                {
                    b.HasOne("CocktailHub.Core.Entities.Cocktail", "Cocktail")
                        .WithMany("Favorites")
                        .HasForeignKey("CocktailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CocktailHub.Core.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cocktail");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.Cocktail", b =>
                {
                    b.Navigation("CocktailIngredients");

                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.Country", b =>
                {
                    b.Navigation("Cocktails");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.Ingredient", b =>
                {
                    b.Navigation("CocktailIngredients");
                });

            modelBuilder.Entity("CocktailHub.Core.Entities.User", b =>
                {
                    b.Navigation("CreatedCocktails");

                    b.Navigation("Favorites");
                });
#pragma warning restore 612, 618
        }
    }
}
